version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - .db/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banco_teste
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 2048M
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: